### ISSUE TITLE
Sign proposal data helper

### ISSUE THREAD

**Issue by jtrein** [openlawteam/tribute-ui#27]
When we need to submit a proposal to Moloch v3 and Snapshot, there is core data which both require.

- Snapshot needs the proposal data to create a Snapshot proposal
- Moloch v3 needs the proposal data to make a hash out of it in the EVM on proposal submission

---

**Todo's**

- [x] Types for core proposal data
- [x] Config for proposal vote choices `["yes", "no"]`
- [x] Config for proposal environment-specific vote length in seconds
- [x] Config for proposal snapshot `space`
- [x] Function `{proposalData, signature} = await func(data: CoreProposalData)`
- [x] Copy `offchain_voting.js` from `laoland`
- [x] Unit test

---

**References**

- [Proposal data example](https://github.com/openlawteam/laoland/blob/bec8f490582456e1b964e604d46ec324408bbf2a/test/adapters/offchain.voting.test.js#L251)
- [Signature function we need to copy](https://github.com/openlawteam/laoland/blob/bec8f490582456e1b964e604d46ec324408bbf2a/utils/offchain_voting.js#L170)
